### PR TITLE
Don't accept Ed's compliments

### PR DESCRIPTION
**Pull request by blunket**
lol

### CODE REVIEW

**Comment by hitjim** [comment]
I'm so jealous that I missed the chance to review this PR.

**Comment by jcbwlkr** [comment]
You still can! 😀

**Comment by swiftcode** [comment]
Is this "bang bang 1 bang" a typo or a meme (it's so difficult to tell anymore)

> 'leave me alone already, Ed!!1!'

**Comment by blunket** [comment]
haha, a meme.

(also hopefully the back to the future reference was clear with the "make like a tree and get out of here" joke)

**Pull request merged**
