### PR TITLE
Bot tewt - you're welcome

### PR DESCRIPTION
**Pull request by hitjim**
Resolves Issue #6

### CODE REVIEW

**Comment by hitjim** [comment]
So... what are you waiting on?  :D

**Comment by jcbwlkr** [comment]
I was waiting on #44 to land. How about we make these reactions instead of messages?

**Comment by hitjim** [comment]
Wasn't sure if this way was better since it would look like bot was 💨 💩 -ing, and perhaps the message would get lost if they ended up as reactions to the person issuing the `bot fart` 

You know, b/c UX is crucial here.  The likelihood of it getting triggered also seemed low enough, and the 1 to 2 emoji seemed harmless enough to put in a message response?

I'm down for either, though.

**Comment by hitjim** [comment]
blewp?

**Comment by hitjim** [comment]
💨

**Pull request merged**
